name: 'Run phpcs with reviewdog'
description: 'Run phpcs with reviewdog on pull requests to improve code review experience.'
author: 'Gene Chen (geneccx)'
inputs:
  github_token:
    description: 'GITHUB_TOKEN.'
    required: true
  reporter:
    description: 'Reporter of reviewdog command [github-pr-check,github-pr-review].'
    default: 'github-pr-check'
  phpcs_args:
    description: 'Arguments to pass to phpcs'
    default: '.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github_token }}
    - ${{ inputs.reporter }}
    - ${{ inputs.phpcs_args }}
branding:
  icon: 'edit'
  color: 'gray-dark'
